# Generated by Django 2.1.2 on 2020-01-22 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0079_auto_20191028_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('archivo', models.FileField(upload_to='adjuntos_tareas')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('comentario', models.TextField()),
                ('es_devolucion', models.BooleanField()),
                ('adjuntos', models.ManyToManyField(null=True, to='tareas.Adjunto')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('obligatoria', models.BooleanField()),
                ('adjuntos', models.ManyToManyField(null=True, to='tareas.Adjunto')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TareaAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('aprobada', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='tareas.Tarea')),
            ],
        ),
        migrations.AddField(
            model_name='devolucion',
            name='tarea_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.TareaAlumno'),
        ),
        migrations.AlterUniqueTogether(
            name='tareaalumno',
            unique_together={('tarea', 'estudiante')},
        ),
    ]
