# Generated by Django 2.1.2 on 2020-01-27 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_auto_20200126_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunto',
            name='archivo',
            field=models.FileField(upload_to='adjuntos_tareas', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'pdf', 'xls', 'xlsx'])]),
        ),
    ]
