# Generated by Django 2.1.2 on 2020-02-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_auto_20200127_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaalumno',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_alumnos', to='tareas.Tarea'),
        ),
    ]
