# Generated by Django 2.2.17 on 2021-05-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_auto_20200207_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='adjuntos',
            field=models.ManyToManyField(to='tareas.Adjunto'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='adjuntos',
            field=models.ManyToManyField(blank=True, to='tareas.Adjunto'),
        ),
    ]
