# Generated by Django 2.1.2 on 2018-11-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0045_area'),
        ('users', '0005_auto_20180907_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cursos.Area'),
        ),
        migrations.AddField(
            model_name='user',
            name='enabled_courses',
            field=models.ManyToManyField(related_name='enabled_users', to='cursos.Course'),
        ),
    ]
