# Generated by Django 2.1.2 on 2018-11-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181127_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cursos.Area'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enabled_courses',
            field=models.ManyToManyField(related_name='enabled_users', to='cursos.Course'),
        ),
    ]
