# Generated by Django 2.1.2 on 2018-11-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181127_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enabled_courses',
            field=models.ManyToManyField(null=True, related_name='enabled_users', to='cursos.Course'),
        ),
    ]
