# Generated by Django 2.1.2 on 2018-11-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181127_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enabled_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='enabled_users', to='cursos.Course'),
        ),
    ]
