# Generated by Django 2.1.2 on 2018-12-07 00:33

import django.core.validators
from django.db import migrations, models
import re
import users.models


def resave_all_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    db_alias = schema_editor.connection.alias

    for u in User.objects.using(db_alias).all():
        u.save()

def reverse_resave_all_users(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181128_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area',
        ),
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=63, null=True, validators=[django.core.validators.RegexValidator(re.compile('((?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\\.)+)(?:[A-Z0-9-]{2,63}(?<!-))\\Z', 2), message='El valor ingresado no es un dominio válido'), users.models.no_at_validator], verbose_name='Dominio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enabled_courses',
            field=models.ManyToManyField(blank=True, help_text='Son los cursos que tiene habilitados este socio de manera directa. Tener en cuenta que también podrá acceder a los cursos que estén habilitados para su área/departamento/sector y a los cursos en los que ya esté inscripto.', null=True, related_name='enabled_users', to='cursos.Course', verbose_name='Cursos habilitados'),
        ),
        migrations.RunPython(resave_all_users, reverse_code=reverse_resave_all_users),
    ]
