# Generated by Django 2.1.2 on 2019-07-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181207_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enabled_courses',
            field=models.ManyToManyField(blank=True, help_text='Son los cursos que tiene habilitados este socio de manera directa. Tener en cuenta que también podrá acceder a los cursos que estén habilitados para su área/departamento/sector y a los cursos en los que ya esté inscripto.', related_name='enabled_users', to='cursos.Course', verbose_name='Cursos habilitados'),
        ),
    ]
