# Generated by Django 2.1.2 on 2019-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190702_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
