# Generated by Django 2.1.2 on 2019-08-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_is_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_stakeholder',
            field=models.BooleanField(default=False),
        ),
    ]
