# Generated by Django 2.2.17 on 2021-07-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_externaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=9, verbose_name='DNI'),
        ),
    ]
