# Generated by Django 2.2.17 on 2021-05-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimeo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(editable=False, null=True)),
                ('genially_id', models.CharField(blank=True, default='', max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('order', models.PositiveIntegerField()),
                ('type_of_segment', models.CharField(choices=[('V', 'Video'), ('S', 'Slide'), ('L', 'Live'), ('G', 'Genially')], default='V', max_length=1)),
                ('thumb_path', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='segment_thumbnails')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
