# Generated by Django 2.2.17 on 2021-05-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicsegment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
