# Generated by Django 2.2.17 on 2021-06-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20210615_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicsegment',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='publicsegment',
            name='open_external_link_in',
            field=models.CharField(blank=True, choices=[('_self', '_self'), ('_blank', '_blank')], max_length=30),
        ),
    ]
