# Generated by Django 2.1.2 on 2019-07-22 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forummessage',
            name='delete_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forummessage',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forummessage',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
