# Generated by Django 2.1.2 on 2019-07-26 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foros', '0003_auto_20190722_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='forummessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forummessage',
            name='delete_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_forum_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forummessage',
            name='segment_tracking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.SegmentTracking'),
        ),
    ]
