# Generated by Django 2.1.2 on 2019-07-26 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0004_auto_20190726_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forummessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
