# Generated by Django 2.1.2 on 2019-07-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0005_auto_20190726_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forummessage',
            name='edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='forummessage',
            name='segment_tracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.SegmentTracking'),
        ),
    ]
