# Generated by Django 2.1.2 on 2019-07-30 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0006_auto_20190726_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['segment', 'order', 'title']},
        ),
        migrations.AddField(
            model_name='forummessage',
            name='replies_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foros.ForumMessage'),
        ),
    ]
