# Generated by Django 2.1.2 on 2020-04-30 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0081_auto_20200427_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimeo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(editable=False, null=True)),
                ('rtmp_url', models.URLField(blank=True)),
                ('stream_key', models.UUIDField(blank=True, default=None, null=True, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.Segment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
