# Generated by Django 2.1.2 on 2020-05-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_auto_20200501_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='is_live',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts', to='cursos.Segment'),
        ),
    ]
