# Generated by Django 2.1.2 on 2020-05-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_auto_20200506_1726'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='broadcast',
            unique_together=set(),
        ),
    ]
