# Generated by Django 2.1.2 on 2020-05-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_auto_20200507_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='stream_key',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
