# Generated by Django 2.1 on 2018-08-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20180815_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vimeo_id',
            field=models.PositiveIntegerField(default=59777392),
            preserve_default=False,
        ),
    ]
