# Generated by Django 2.1 on 2018-08-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_questionnaireoption_selected_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairequestion',
            name='answer_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
