# Generated by Django 2.1 on 2018-08-24 05:41

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_auto_20180823_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairequestion',
            name='answer_timestamp',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='answered'),
        ),
    ]
