# Generated by Django 2.1 on 2018-08-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_auto_20180824_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
