# Generated by Django 2.1 on 2018-08-27 14:51

import cursos.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_video_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotracking',
            name='parts_watched',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=cursos.models.emptyPartsWatched, size=None),
        ),
    ]
