# Generated by Django 2.1 on 2018-08-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_auto_20180826_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='course_thumbnails'),
        ),
        migrations.AlterField(
            model_name='video',
            name='document',
            field=models.FileField(null=True, upload_to='video_documents'),
        ),
    ]
