# Generated by Django 2.1 on 2018-08-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_video_duration'),
        ('cursos', '0012_auto_20180827_1922'),
    ]

    operations = [
    ]
