# Generated by Django 2.1 on 2018-08-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text_after_correct_answer',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='question',
            name='text_after_incorrect_answer',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
