# Generated by Django 2.1 on 2018-08-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_auto_20180830_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='course_thumbnails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='question_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='document',
            field=models.FileField(blank=True, default='', upload_to='video_documents'),
            preserve_default=False,
        ),
    ]
