# Generated by Django 2.1.1 on 2018-09-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_auto_20180830_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='min_correct_questions',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
