# Generated by Django 2.1.1 on 2018-09-07 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_video_min_correct_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='next_allowed_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cursos.Video'),
        ),
    ]
