# Generated by Django 2.1.1 on 2018-09-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0020_courseenrollment_next_allowed_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotracking',
            name='user_has_downloaded_document',
            field=models.BooleanField(default=False),
        ),
    ]
