# Generated by Django 2.1.1 on 2018-09-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0022_auto_20180907_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text_after_correct_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_after_incorrect_answer',
            field=models.TextField(blank=True),
        ),
    ]
