# Generated by Django 2.1.1 on 2018-09-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0024_auto_20180907_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
