# Generated by Django 2.1.1 on 2018-09-18 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0025_course_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('document', models.FileField(blank=True, upload_to='video_documents')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.Video')),
            ],
        ),
    ]
