# Generated by Django 2.1.1 on 2018-09-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0027_auto_20180918_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='document',
        ),
    ]
