# Generated by Django 2.1.1 on 2018-09-20 14:55

from django.db import migrations


## DATA MIGRATION

def move_download_tracking_data(apps, schema_editor):
    Video = apps.get_model('cursos', 'Video')
    DownloadableDocument = apps.get_model('cursos', 'DownloadableDocument')
    DownloadableDocumentTracking = apps.get_model('cursos', 'DownloadableDocumentTracking')
    VideoTracking = apps.get_model('cursos', 'VideoTracking')
    for vt in VideoTracking.objects.all():
        if vt.user_has_downloaded_document:
            document = DownloadableDocument.objects.get(video=vt.video)
            DownloadableDocumentTracking.objects.create(document=document, user=vt.user)
        

class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0029_auto_20180918_1913'),
    ]

    operations = [
        migrations.RunPython(move_download_tracking_data),
    ]

