# Generated by Django 2.1.1 on 2018-09-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0030_download_tracking_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadabledocument',
            name='document',
            field=models.FileField(upload_to='video_documents'),
        ),
    ]
