# Generated by Django 2.1.1 on 2018-09-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0031_auto_20180920_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotracking',
            name='user_has_downloaded_all_documents',
            field=models.BooleanField(default=False),
        ),
    ]
