# Generated by Django 2.1.1 on 2018-10-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0034_allowedemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Segment',
        ),
    ]
