# Generated by Django 2.1.1 on 2018-10-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0036_auto_20181009_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='first_slide',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursos.Slide'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='type_of_segment',
            field=models.CharField(choices=[('V', 'Video'), ('S', 'Slide')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='slide',
            name='next_slide',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_slide', to='cursos.Slide'),
        ),
    ]
