# Generated by Django 2.1.1 on 2018-10-09 15:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0038_auto_20181009_1501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoTracking',
            new_name='SegmentTracking',
        ),
    ]
