# Generated by Django 2.1.1 on 2018-10-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0039_auto_20181009_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenttracking',
            name='last_slide_shown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursos.Slide'),
        ),
    ]
