# Generated by Django 2.1.1 on 2018-10-10 15:35

import cursos.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0040_segmenttracking_last_slide_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenttracking',
            name='slides_seen',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=cursos.models.emptyPartsWatched, size=None),
        ),
    ]
