# Generated by Django 2.1.2 on 2018-11-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0041_segmenttracking_slides_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadabledocument',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
    ]
