# Generated by Django 2.1.2 on 2018-11-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0042_downloadabledocument_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.ImageField(null=True, upload_to='course_certificate'),
        ),
    ]
