# Generated by Django 2.1.2 on 2018-11-27 20:41

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0043_course_certificate_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(re.compile('((?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\\.)+)(?:[A-Z0-9-]{2,63}(?<!-))\\Z', 2), message='El valor ingresado no es un dominion válido')])),
            ],
        ),
    ]
