# Generated by Django 2.1.2 on 2018-11-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0044_alloweddomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('enabled_courses', models.ManyToManyField(to='cursos.Course')),
            ],
            options={
                'verbose_name': 'Área/Departamento/Sector',
                'verbose_name_plural': 'Áreas/Departamentos/Sectores',
                'ordering': ['name'],
            },
        ),
    ]
