# Generated by Django 2.1.2 on 2018-11-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0045_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='enabled_courses',
            field=models.ManyToManyField(related_name='enabled_areas', to='cursos.Course'),
        ),
    ]
