# Generated by Django 2.1.2 on 2018-11-27 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0046_auto_20181127_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_query_name='enrollments', to='cursos.Course'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_query_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
