# Generated by Django 2.1.2 on 2018-11-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0047_auto_20181127_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='enabled_courses',
            field=models.ManyToManyField(null=True, related_name='enabled_areas', to='cursos.Course'),
        ),
    ]
