# Generated by Django 2.1.2 on 2018-11-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0048_auto_20181127_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedemail',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursos.Area'),
        ),
        migrations.AlterField(
            model_name='area',
            name='enabled_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='enabled_areas', to='cursos.Course'),
        ),
    ]
