# Generated by Django 2.1.2 on 2018-12-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0050_auto_20181207_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='questions_to_ask',
            field=models.PositiveIntegerField(default=0, help_text='Es la cantidad de preguntas a utilizar para \n    armar el cuestionario. Si es 0 se utilizan siempre todas. Si es N mayor a 0 el cuestionario se arma toman N \n    preguntas de las que haya definidas para este segmento. Si hay definidas menos de N se tomarán todas.'),
        ),
    ]
