# Generated by Django 2.1.2 on 2019-01-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0052_segmenttracking_last_part_watched'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('questions_to_ask', models.PositiveIntegerField(default=0, help_text='Es la cantidad de preguntas a utilizar para \n        armar el cuestionario. Si es 0 se utilizan siempre todas. Si es N mayor a 0 el cuestionario se arma toman N \n        preguntas de las que haya definidas para este segmento. Si hay definidas menos de N se tomarán todas.')),
            ],
            options={
                'ordering': ['segment', 'order'],
            },
        ),
        migrations.AlterField(
            model_name='segment',
            name='questions_to_ask',
            field=models.PositiveIntegerField(default=0, help_text='Es la cantidad de preguntas a utilizar para \n            armar el cuestionario. Si es 0 se utilizan siempre todas. Si es N mayor a 0 el cuestionario se arma toman N \n            preguntas de las que haya definidas para este segmento. Si hay definidas menos de N se tomarán todas.'),
        ),
        migrations.AddField(
            model_name='segmentsection',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cursos.Segment'),
        ),
        migrations.AlterUniqueTogether(
            name='segmentsection',
            unique_together={('segment', 'order')},
        ),
    ]
