# Generated by Django 2.1.2 on 2019-01-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0056_remove_question_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='questions_to_ask',
        ),
    ]
