# Generated by Django 2.1.2 on 2019-05-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0057_remove_segment_questions_to_ask'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenttracking',
            name='watched_full_at',
            field=models.DateTimeField(null=True),
        ),
    ]
