# Generated by Django 2.1.2 on 2019-05-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0057_remove_segment_questions_to_ask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('image', models.ImageField(blank=True, upload_to='category_thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate_template',
            field=models.ImageField(blank=True, null=True, upload_to='course_certificate', verbose_name='Plantilla del certificado'),
        ),
        migrations.AddField(
            model_name='categorycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Course'),
        ),
    ]
