# Generated by Django 2.1.2 on 2019-06-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0059_usersevolutionreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersevolutionreport',
            name='file',
            field=models.FileField(null=True, upload_to='reports'),
        ),
        migrations.AlterField(
            model_name='usersevolutionreport',
            name='finished',
            field=models.DateTimeField(null=True),
        ),
    ]
