# Generated by Django 2.1.2 on 2019-07-02 23:16

from django.db import migrations, models


def save_has_passed(apps, schema_editor):
    Questionnaire = apps.get_model('cursos', 'Questionnaire')
    for q in Questionnaire.objects.all():
        if q.is_complete:
            if q.questionnairequestion_set.filter(answered_correctly=True).count() >= q.video.min_correct_questions:
                q.has_passed = True
            else:
                q.has_passed = False
        else:
            q.has_passed = False
        q.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0061_auto_20190702_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='has_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(save_has_passed),
    ]
