# Generated by Django 2.1.2 on 2019-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0061_auto_20190531_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorycourse',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorycourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
        migrations.AddField(
            model_name='course',
            name='categories_temporary',
            field=models.ManyToManyField(related_name='courses', to='cursos.Category'),
        ),
        migrations.DeleteModel(
            name='CategoryCourse',
        ),
    ]
