# Generated by Django 2.1.2 on 2019-05-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0062_auto_20190531_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='categories_temporary',
            new_name='categories',
        ),
    ]
