# Generated by Django 2.1.2 on 2019-07-02 23:54

from django.db import migrations, models


def save_correct_has_passed_questionnaire_data(apps, schema_editor):
    SegmentTracking = apps.get_model('cursos', 'SegmentTracking')
    Questionnaire = apps.get_model('cursos', 'Questionnaire')
    for st in SegmentTracking.objects.all():
        for _ in Questionnaire.objects.filter(video=st.video, user=st.user, is_complete=True, has_passed=True):
            st.has_passed_questionnaire = True
            st.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0062_questionnaire_has_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenttracking',
            name='has_passed_questionnaire',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(save_correct_has_passed_questionnaire_data),
    ]
