# Generated by Django 2.1.2 on 2019-05-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0063_auto_20190531_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
    ]
