# Generated by Django 2.1.2 on 2019-07-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0063_segmenttracking_has_passed_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='enabled_since',
            field=models.DateTimeField(null=True),
        ),
    ]
