# Generated by Django 2.1.2 on 2019-07-15 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0065_segment_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'is_tutor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
