# Generated by Django 2.1.2 on 2019-07-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0066_course_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='enabled_since',
            field=models.DateTimeField(blank=True, help_text='Indica a partir de qué fecha se puede acceder a este segmento', null=True, verbose_name='Fecha de habilitación'),
        ),
    ]
