# Generated by Django 2.1.2 on 2019-07-03 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0066_course_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedemail',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allowed_email', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
