# Generated by Django 2.1.2 on 2019-08-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0069_auto_20190801_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersEvolutionPerCourseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(null=True)),
                ('present', models.BooleanField(default=False)),
                ('file', models.FileField(null=True, upload_to='reports')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Course')),
            ],
        ),
    ]
