# Generated by Django 2.1.2 on 2019-08-20 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0074_auto_20190813_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_tutor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
