# Generated by Django 2.1.2 on 2019-08-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0066_auto_20190603_1336'),
        ('cursos', '0068_auto_20190703_1657'),
        ('cursos', '0075_auto_20190820_1411'),
    ]

    operations = [
    ]
