# Generated by Django 2.1.2 on 2019-08-22 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0076_merge_20190821_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedemail',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allowed_email', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
