# Generated by Django 2.1.2 on 2019-09-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0077_auto_20190822_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['course', 'order']},
        ),
        migrations.AlterField(
            model_name='segment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='segment_thumbnails'),
        ),
    ]
