# Generated by Django 2.1.2 on 2019-10-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0078_auto_20190905_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='first_slide',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segment', to='cursos.Slide'),
        ),
    ]
