# Generated by Django 2.1.2 on 2020-04-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0080_auto_20200427_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='type_of_segment',
            field=models.CharField(choices=[('V', 'Video'), ('S', 'Slide'), ('L', 'Live')], default='V', max_length=1),
        ),
    ]
