# Generated by Django 2.1.2 on 2020-05-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0082_auto_20200501_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='cursos.Course'),
        ),
    ]
