# Generated by Django 2.1.2 on 2020-06-08 20:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0084_auto_20200507_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Costo'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_currency',
            field=models.CharField(choices=[('ARS', '$ Argentinos'), ('BRL', 'R$ Real'), ('USD', 'u$s Dólar EEUU')], default='BRL', max_length=3, verbose_name='Moneda'),
        ),
    ]
