# Generated by Django 2.1.2 on 2020-08-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0085_auto_20200608_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_area',
            field=models.ForeignKey(help_text='Es el área que se asignará a los usuarios que se registren sin que previamente exista un "Email habilitado" para ellos', null=True, on_delete=django.db.models.deletion.PROTECT, to='cursos.Area', verbose_name='Área por defecto'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='requires_allowed_email',
            field=models.BooleanField(default=True, help_text='Indica si para que un usuario pueda registrarse se requiere que su email se encuentre cargado en "Emails habilitados" con anterioridad. En caso de que no se necesita generar un Área para utilizar como área por defecto y configurarla', verbose_name='Requiere emails habilitados'),
        ),
    ]
