# Generated by Django 2.2.17 on 2021-05-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0087_auto_20201023_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='type_of_segment',
            field=models.CharField(choices=[('V', 'Video'), ('S', 'Slide'), ('L', 'Live'), ('G', 'Genially')], default='V', max_length=1),
        ),
    ]
