# Generated by Django 2.2.17 on 2021-05-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0088_auto_20210505_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='genially_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
