# Generated by Django 2.2.17 on 2021-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0089_segment_genially_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='type_of_segment',
            field=models.CharField(choices=[('V', 'Video'), ('S', 'Slide'), ('L', 'Live'), ('G', 'Genially'), ('X', 'Genérico')], default='V', max_length=1),
        ),
    ]
