# Generated by Django 2.2.17 on 2021-06-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0090_auto_20210615_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='embed_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
