# Generated by Django 2.1.2 on 2019-06-04 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0066_course_tutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_mensaje', models.DateTimeField()),
                ('fecha_ultima_interaccion_iniciador', models.DateTimeField(null=True)),
                ('fecha_ultima_interaccion_destinatario', models.DateTimeField(null=True)),
                ('permite_responder', models.BooleanField(default=True)),
                ('asunto', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.Course')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('iniciador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_iniciadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneradorConversaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permite_responder', models.BooleanField(default=True)),
                ('asunto', models.CharField(max_length=50)),
                ('cuerpo', models.TextField(max_length=250)),
                ('areas_destino', models.ManyToManyField(to='cursos.Area')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.Course')),
                ('cursos_destino', models.ManyToManyField(related_name='generadores_conversaciones', to='cursos.Course')),
                ('dominios_destino', models.ManyToManyField(to='cursos.AllowedDomain')),
                ('iniciador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generadores_conversaciones', to=settings.AUTH_USER_MODEL)),
                ('usuarios_destino', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_leido', models.DateTimeField(null=True)),
                ('cuerpo', models.TextField()),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.Conversacion')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
