# Generated by Django 2.1.2 on 2019-06-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_mensaje_responde_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='generada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mensajes.GeneradorConversaciones'),
        ),
    ]
