# Generated by Django 2.1.2 on 2019-06-13 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_conversacion_generada_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacion',
            name='iniciador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conv_iniciadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generadorconversaciones',
            name='cursos_destino',
            field=models.ManyToManyField(related_name='generador_conv_destino', to='cursos.Course'),
        ),
        migrations.AlterField(
            model_name='generadorconversaciones',
            name='iniciador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generador_conv_iniciados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='mensajes.Conversacion'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
