# Generated by Django 2.1.2 on 2019-06-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0004_auto_20190613_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='generadorconversaciones',
            name='curso_solo_inscriptos',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='generada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conv_generadas', to='mensajes.GeneradorConversaciones'),
        ),
    ]
