# Generated by Django 2.1.2 on 2019-08-13 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0074_auto_20190813_1459'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('texto', models.CharField(max_length=200)),
                ('obligatoria', models.BooleanField(default=False)),
                ('inicio', models.DateTimeField()),
                ('vencimiento', models.DateTimeField()),
                ('imagen', models.ImageField(null=True, upload_to='encuestas')),
                ('mensaje_gracias', models.CharField(max_length=50, null=True)),
                ('dominios_target', models.ManyToManyField(to='cursos.AllowedDomain')),
                ('sectores_target', models.ManyToManyField(to='cursos.Area')),
                ('usuarios_target', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Encuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('tipo', models.CharField(choices=[('EXCLUYENTE', 'Pregunta excluyente'), ('ADITIVA', 'Pregunta aditiva'), ('TEXTO', 'Pregunta de texto'), ('ESTRELLAS', 'Calificación con estrellas'), ('PULGARES', 'Calificación con pulgares')], max_length=20)),
                ('texto', models.CharField(max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='encuestas/preguntas')),
                ('aditiva_debe_contestar_al_menos_una', models.BooleanField(default=True)),
                ('texto_estrella_1', models.CharField(blank=True, max_length=40)),
                ('texto_estrella_2', models.CharField(blank=True, max_length=40)),
                ('texto_estrella_3', models.CharField(blank=True, max_length=40)),
                ('texto_estrella_4', models.CharField(blank=True, max_length=40)),
                ('texto_estrella_5', models.CharField(blank=True, max_length=40)),
                ('texto_pulgar_arriba', models.CharField(blank=True, max_length=40)),
                ('texto_pulgar_abajo', models.CharField(blank=True, max_length=40)),
                ('imagen_pulgar_arriba', models.ImageField(null=True, upload_to='encuestas/preguntas')),
                ('imagen_pulgar_abajo', models.ImageField(null=True, upload_to='encuestas/preguntas')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='encuestas.Encuesta')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('texto', models.CharField(blank=True, max_length=256)),
                ('estrellas', models.PositiveSmallIntegerField(null=True)),
                ('pulgar', models.BooleanField(null=True)),
                ('opciones', models.ManyToManyField(to='encuestas.OpcionPregunta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Pregunta')),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.EncuestaTracking')),
            ],
        ),
        migrations.AddField(
            model_name='opcionpregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='encuestas.Pregunta'),
        ),
    ]
