# Generated by Django 2.1.2 on 2019-08-14 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='encuestas'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='mensaje_gracias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='encuestas/preguntas'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='imagen_pulgar_abajo',
            field=models.ImageField(blank=True, null=True, upload_to='encuestas/preguntas'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='imagen_pulgar_arriba',
            field=models.ImageField(blank=True, null=True, upload_to='encuestas/preguntas'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='estrellas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuestas.Pregunta'),
        ),
        migrations.AlterUniqueTogether(
            name='encuestatracking',
            unique_together={('encuesta', 'usuario')},
        ),
    ]
