# Generated by Django 2.1.2 on 2019-08-15 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_auto_20190814_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='dominios_target',
            field=models.ManyToManyField(blank=True, to='cursos.AllowedDomain'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='sectores_target',
            field=models.ManyToManyField(blank=True, to='cursos.Area'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='usuarios_target',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
