# Generated by Django 2.1.2 on 2019-08-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_auto_20190815_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestatracking',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='encuestatracking',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='encuestas.Encuesta'),
        ),
        migrations.AlterField(
            model_name='opcionpregunta',
            name='pregunta',
            field=models.ForeignKey(limit_choices_to=models.Q(('tipo', 'EXCLUYENTE'), ('tipo', 'ADITIVA'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='encuestas.Pregunta'),
        ),
    ]
