# Generated by Django 2.1.2 on 2019-08-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_auto_20190815_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='donde',
            field=models.CharField(choices=[('LOGIN', 'Al iniciar sesion'), ('FIN_CURSO', 'Al finalizar un curso'), ('INICIAR_CURSO', 'Al iniciar o continuar un curso')], default='INICIAR_CURSO', max_length=50),
        ),
    ]
