# Generated by Django 2.1.2 on 2019-08-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_encuesta_donde'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestatracking',
            name='snoozed',
            field=models.BooleanField(default=False),
        ),
    ]
