# Generated by Django 2.1.2 on 2019-08-21 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0006_encuestatracking_snoozed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('tracking', 'pregunta')},
        ),
    ]
