# Generated by Django 2.1.2 on 2019-08-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0077_auto_20190822_1349'),
        ('encuestas', '0007_auto_20190821_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='cursos.Course'),
        ),
    ]
