# Generated by Django 2.1.2 on 2019-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0008_encuesta_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
