# Generated by Django 2.1.2 on 2019-08-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0009_auto_20190822_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='donde',
            field=models.CharField(choices=[('LOGIN', 'Al iniciar sesion'), ('FIN_CURSO', 'Al finalizar un curso'), ('INICIO_CURSO', 'Al iniciar o continuar un curso')], default='INICIO_CURSO', max_length=50),
        ),
    ]
