# Generated by Django 2.1.2 on 2019-08-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0010_auto_20190822_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestatracking',
            name='iniciada',
            field=models.BooleanField(default=True),
        ),
    ]
